### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by hadrilec** [pyr-opendatafr/graffiti#5]
Apparently with shinapps.io free trial the memory limit for one app is 1GB, which is preventing us from deploying it so far.
Consequently, graffiti deployment should be done with sppcloud. 
An old environment used for deployment can be found here : https://github.com/hadrilec/graffiti-env/blob/master/Dockerfile
Otherwise this repo might help : https://github.com/InseeFrLab/template-shiny-deployment

**Comment by jdesclodure** [comment]
Hi Hadrien! 
Do you still have access to sspcloud ? If you don't then I have access to it but I only deployed a "Hello world" shiny app to see how it works.
BTW, is it ok to deploy a shiny app permanently on sspcloud ?
Best regards, Julien

**Comment by hadrilec** [comment]
Julien, if you want to deploy the app on sspcloud please do, it will be very much appreciated on my side.
As long as it is an innovation-related project I guess no one will complain about having graffiti deployed on sspcloud. On the contrary, some previous users had asked me to do so.
I let you get in touch with the innovation team at Insee to have a confirmation.
It would be nice to have a dedicated repo on GitHub for the environment of the app, as a copy of Insee's gitlab repo.
Best,

**Comment by jdesclodure** [comment]
Yeah I will try to do it! I think the guys at the SSP cloud project won't mind it ; I'll talk to Romain A. about it.

A few questions on the deployment:

1. About the app's environment repo based on the gitlab one, should I duplicate it on my account or do you want to do it on yours ?
2. For my "Hello world" shiny app, I used DockerHub to host the image. However my DockerHub account is not pro and a ci.yaml file won't update the docker image without a pro account. Is it a problem ? If so, do you know a better docker image host ?
3. I don't really know how to configure the shiny app on the ssp cloud so that it will be able to allow http request to the api but I'll ask you questions about it later.

Best regards, Julien

**Comment by hadrilec** [comment]
1. I think we can move graffiti-poc and the future graffiti-env repos to the organization I had created to host open data projects: https://github.com/pyr-opendatafr
2. Regarding Docker, I do not know but if you get in touch with the innovation team for sure they would advice something relevant about it.
3. Graffiti is using so far only SDMX queries and does not query api.insee.fr. At this stage there is no need for dedicated credentials for the app to run.

**Comment by jdesclodure** [comment]
I tried to understand how to create the dockerfile for graffiti but there are many things that I'm not sure (debian packages to install and which R packages to install in addition of those of the app). Moreover when I tried to generate a docker image it took a _very_ long time on my (low-cpu) pc and low internet connection. So, Hadrien, I hope you will be able to handle it because it's out of my league apparently!
Meanwhile I wrote to SSP cloud project for a permanent shiny instance and I'll also ask regarding Docker.

**Comment by jdesclodure** [comment]
I gave it an other try and I finally succeeded! The website is [here](https://graffiti-poc.lab.sspcloud.fr/) with 30Ghz CPU and 50Go of RAM but I'm still note sure how long this rstudio service will last on datalab.sspcloud.fr. By the way I couldn't use graffiti.lab.sspcloud.fr because you still had this address registered to you according to the server.

Here is the dockerfile I used:
```
# Base image
FROM rocker/shiny:4.1.2

# Install required linux librairies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libpq-dev \
                                               libssl-dev \
                                               libxml2-dev \
                                               libcurl4-openssl-dev \
                                               build-essential \
                                               libudunits2-dev \
                                               libharfbuzz-dev \ 
                                               libfribidi-dev \
                                               libfreetype6-dev \
                                               libpng-dev \
                                               libtiff5-dev \
                                               libjpeg-dev \
                                               libfontconfig1-dev

ENV no_proxy=".sspcloud.fr, .mesos,.thisdcos.directory,.dcos.directory,.zk,127.0.0.1,localhost,.intra,.insee.test,.innovation.insee.eu,.mesos,master.mesos,.thisdcos.directory,.dcos.directory,.zk,127.0.0.1,10.192.255.21,10.192.255.22,10.192.254.31,10.192.254.32,10.192.254.33,10.192.253.51,10.192.253.52,10.192.253.53,10.192.253.54,10.192.253.55,10.192.253.56,10.192.253.57,10.192.253.58,10.192.253.59,10.192.253.61,10.192.253.62,10.192.253.63,10.192.253.64,10.192.1.41,10.192.1.42,9.0.0.0/8,localhost"

# Install R dependencies
RUN R -e "install.packages(c('httr', 'xml2', 'tibble', 'crayon', 'openssl', 'rappdirs', 'shiny', 'shinydashboard', 'shinydashboardPlus', 'shinyWidgets', 'shinyjs', 'DT', 'magrittr', 'lubridate', 'rlang', 'ggplot2', 'plotly', 'rmarkdown', 'RColorBrewer', 'ggthemes', 'png', 'grid', 'purrr'), repos='https://cran.rstudio.com/', dependencies=TRUE)"
RUN R -e "devtools::install_github('pyr-opendatafr/R-Insee-Data')"

# Install R package and its dependencies
COPY graffiti/ ./graffiti
RUN Rscript -e 'install.packages("./graffiti", repos = NULL, type="source")'

# Expose port where shiny app will broadcast
ARG SHINY_PORT=3838
EXPOSE $SHINY_PORT
RUN echo "local({options(shiny.port = ${SHINY_PORT}, shiny.host = '0.0.0.0')})" >> /usr/local/lib/R/etc/Rprofile.site

# Endpoint
CMD ["Rscript", "-e", "graffiti::graffiti()"]

```
Here is the Chart.yaml file:
```
apiVersion: v2
name: shiny-app-template
version: 1.1.0
dependencies:
  - name: shiny
    version: 0.16.0
    repository: https://inseefrlab.github.io/helm-charts
```
And here is the values.yaml file:
```
shiny:
  image:
    repository: jdinsee/graffiti-poc
    tag: "0.1.1"
  ingress:
    enabled: true
    hostname: graffiti-poc.lab.sspcloud.fr
```
The docker image is hosted [here](https://hub.docker.com/r/jdinsee/graffiti-poc/tags).

However I don't think the current settings can be updated with a ci.yaml hosted on the graffiti githubrepo.

What do you think Hadrien of the Docker file? Do you think you can create the env repo ? (because I not sure how to do it properly actually).

Best regards, Julien

**Comment by hadrilec** [comment]
That's amazing! I am so grateful to you! 🚀 
As you made major contributions I have added you as author 6f46a7b2165b16443c321e5c45ecc3640a3377a3

It would prefer to have graffiti.lab.sspcloud.fr, could you ask the innovation team to take it back? You could you this issue as a proof of approval.

I would prefer that you commit yourself the files you have created, I have just set up this repo for that purpose : https://github.com/pyr-opendatafr/graffiti-env

**Comment by jdesclodure** [comment]
That's nice of you!
Concerning the url of the website I will talk to Romain at the innovation team this week and then I will redeploy a version of graffiti.
It's ok for the env files, I will commit them and then you could check/amend the repo.

**Comment by jdesclodure** [comment]
Deployment done at [graffiti.lab.sspcloud.fr](http://graffiti.lab.sspcloud.fr/).
